# SOPS configuration — encrypt secrets with age
# Usage:
#   Encrypt:  sops -e secrets/db.yaml > secrets/db.enc.yaml
#   Decrypt:  sops -d secrets/db.enc.yaml
#   Edit:     sops secrets/db.enc.yaml
creation_rules:
  - path_regex: \.yaml$
    age: age1l7alxja8a86reeqyencwqug8vhkwjp0zyclgrneg2q84crq6ra6qs2k30m
